[package]
name = "rust_editor"
version = "1.1.0"
authors = ["Ankur <ankur222gangwar@gmail.com>"]
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
unicode-segmentation = "1.9.0"